# With 'Obesity based on eating habits & physical cond.' dataset from kaggle we are going to analyse the factors involved.

## This dataset represent 2110 individuals from Colombia, Peru and Mexico

In [31]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

## Loading the data:

In [32]:
raw_data = pd.read_csv(r'E:\Proyects\Python proyects\Datasets\ObesityDataSet_raw_and_data_sinthetic.csv')

In [33]:
data = raw_data.copy()

In [34]:
data

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,Female,21.000000,1.620000,64.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,0.000000,1.000000,no,Public_Transportation,Normal_Weight
1,Female,21.000000,1.520000,56.000000,yes,no,3.0,3.0,Sometimes,yes,3.000000,yes,3.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.000000,1.800000,77.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,2.000000,1.000000,Frequently,Public_Transportation,Normal_Weight
3,Male,27.000000,1.800000,87.000000,no,no,3.0,3.0,Sometimes,no,2.000000,no,2.000000,0.000000,Frequently,Walking,Overweight_Level_I
4,Male,22.000000,1.780000,89.800000,no,no,2.0,1.0,Sometimes,no,2.000000,no,0.000000,0.000000,Sometimes,Public_Transportation,Overweight_Level_II
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,Female,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,no,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,Female,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,no,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,no,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,no,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,no,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

## We need to check if the dataset is clean and ready to be processed

In [35]:
data.shape     # it shows the total number of rowa and columns of the dataset

(2111, 17)

In [36]:
data.columns  # it shows the name of each column

Index(['Gender', 'Age', 'Height', 'Weight', 'family_history_with_overweight',
       'FAVC', 'FCVC', 'NCP', 'CAEC', 'SMOKE', 'CH2O', 'SCC', 'FAF', 'TUE',
       'CALC', 'MTRANS', 'NObeyesdad'],
      dtype='object')

In [37]:
data.dtypes    # it shows the data type of each column

Gender                             object
Age                               float64
Height                            float64
Weight                            float64
family_history_with_overweight     object
FAVC                               object
FCVC                              float64
NCP                               float64
CAEC                               object
SMOKE                              object
CH2O                              float64
SCC                                object
FAF                               float64
TUE                               float64
CALC                               object
MTRANS                             object
NObeyesdad                         object
dtype: object

In [38]:
data.nunique()  # it shows the total number of uniques values in each column of the dataset

Gender                               2
Age                               1402
Height                            1574
Weight                            1525
family_history_with_overweight       2
FAVC                                 2
FCVC                               810
NCP                                635
CAEC                                 4
SMOKE                                2
CH2O                              1268
SCC                                  2
FAF                               1190
TUE                               1129
CALC                                 4
MTRANS                               5
NObeyesdad                           7
dtype: int64

In [39]:
data.count()  # it shows the total number of non-null in each solumn

Gender                            2111
Age                               2111
Height                            2111
Weight                            2111
family_history_with_overweight    2111
FAVC                              2111
FCVC                              2111
NCP                               2111
CAEC                              2111
SMOKE                             2111
CH2O                              2111
SCC                               2111
FAF                               2111
TUE                               2111
CALC                              2111
MTRANS                            2111
NObeyesdad                        2111
dtype: int64

In [40]:
data.info()  # provides basic information about the dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 17 columns):
Gender                            2111 non-null object
Age                               2111 non-null float64
Height                            2111 non-null float64
Weight                            2111 non-null float64
family_history_with_overweight    2111 non-null object
FAVC                              2111 non-null object
FCVC                              2111 non-null float64
NCP                               2111 non-null float64
CAEC                              2111 non-null object
SMOKE                             2111 non-null object
CH2O                              2111 non-null float64
SCC                               2111 non-null object
FAF                               2111 non-null float64
TUE                               2111 non-null float64
CALC                              2111 non-null object
MTRANS                            2111 non-null object
NObeyesdad                        2111 non-null object
dtypes: float64(8), object(9)
memory usage: 280.5+ KB

## We whant to change the values from 'Age' to 0 decimals, 'Height' to 2 decimals and 'Weight' to 1 decimal

In [41]:
data = data.round({'Age': 0, 'Height': 2, 'Weight': 1})
data

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.000000,no,0.000000,1.000000,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.000000,yes,3.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.000000,no,2.000000,1.000000,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.000000,no,2.000000,0.000000,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.000000,no,0.000000,0.000000,Sometimes,Public_Transportation,Overweight_Level_II
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,Female,21.0,1.71,131.4,yes,yes,3.0,3.0,Sometimes,no,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,Female,22.0,1.75,133.7,yes,yes,3.0,3.0,Sometimes,no,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,23.0,1.75,133.7,yes,yes,3.0,3.0,Sometimes,no,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,24.0,1.74,133.3,yes,yes,3.0,3.0,Sometimes,no,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,24.0,1.74,133.5,yes,yes,3.0,3.0,Sometimes,no,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

## We whant to change the values from 'CH2O' to 1 decimal, 'FAF' to  0 decimals and 'TUE' to 1 decimal

In [42]:
data = data.round({'CH2O': 1, 'FAF': 0, 'TUE': 1})
data

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,Female,21.0,1.71,131.4,yes,yes,3.0,3.0,Sometimes,no,1.7,no,2.0,0.9,Sometimes,Public_Transportation,Obesity_Type_III
2107,Female,22.0,1.75,133.7,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0,0.6,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,23.0,1.75,133.7,yes,yes,3.0,3.0,Sometimes,no,2.1,no,1.0,0.6,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,24.0,1.74,133.3,yes,yes,3.0,3.0,Sometimes,no,2.9,no,1.0,0.6,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,24.0,1.74,133.5,yes,yes,3.0,3.0,Sometimes,no,2.9,no,1.0,0.7,Sometimes,Public_Transportation,Obesity_Type_III

In [43]:
data.nunique()  # it shows the new total number of uniques values in each column of the dataset

Gender                              2
Age                                40
Height                             51
Weight                            686
family_history_with_overweight      2
FAVC                                2
FCVC                              810
NCP                               635
CAEC                                4
SMOKE                               2
CH2O                               21
SCC                                 2
FAF                                 4
TUE                                21
CALC                                4
MTRANS                              5
NObeyesdad                          7
dtype: int64

In [44]:
data['Age'].value_counts()    # in a single column it shows all the unique values with their count

21.0    236
23.0    218
26.0    213
18.0    212
19.0    169
22.0    163
20.0    150
24.0     95
25.0     82
17.0     69
31.0     62
30.0     53
27.0     43
33.0     37
38.0     34
29.0     33
34.0     29
32.0     26
39.0     25
37.0     24
28.0     20
16.0     20
41.0     20
40.0     19
35.0     19
36.0      6
44.0      6
42.0      6
55.0      5
43.0      3
45.0      3
46.0      2
51.0      2
15.0      1
56.0      1
14.0      1
52.0      1
48.0      1
61.0      1
47.0      1
Name: Age, dtype: int64

## We whant to change the name of abreviated columnÂ´s name, so we know what info really provides

In [45]:
data.head()    # it shows the 'N' rows in the data, by default N=5

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [46]:
data.rename(columns = {'Height': 'Height (meters)', 'Weight': 'Weight (Kg)', 'FAVC': 'Frequent_consumption_high_caloric_food', 'FCVC': 'Frequency_consumption_vegetables',
                      'NCP': 'Number_main_meals_a_day', 'CAEC': 'Consumption_food_between_meals', 'CH2O': 'Daily_water_consumption', 'SCC': 'Calories_consumption_monitoring',
                       'FAF': 'Physical_activity_frequency (days/week)', 'TUE': 'Time_using_technology_devices (hours)', 'CALC': 'Consumption_of_alcohol', 'MTRANS': 'Transportation_used',
                      'family_history_with_overweight': 'Family_history_with_overweight'}, inplace=True)

In [48]:
data

,Gender,Age,Height (meters),Weight (Kg),Family_history_with_overweight,Frequent_consumption_high_caloric_food,Frequency_consumption_vegetables,Number_main_meals_a_day,Consumption_food_between_meals,SMOKE,Daily_water_consumption,Calories_consumption_monitoring,Physical_activity_frequency (days/week),Time_using_technology_devices (hours),Consumption_of_alcohol,Transportation_used,NObeyesdad
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,Female,21.0,1.71,131.4,yes,yes,3.0,3.0,Sometimes,no,1.7,no,2.0,0.9,Sometimes,Public_Transportation,Obesity_Type_III
2107,Female,22.0,1.75,133.7,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0,0.6,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,23.0,1.75,133.7,yes,yes,3.0,3.0,Sometimes,no,2.1,no,1.0,0.6,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,24.0,1.74,133.3,yes,yes,3.0,3.0,Sometimes,no,2.9,no,1.0,0.6,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,24.0,1.74,133.5,yes,yes,3.0,3.0,Sometimes,no,2.9,no,1.0,0.7,Sometimes,Public_Transportation,Obesity_Type_III

In [49]:
data['NObeyesdad'].value_counts()

Obesity_Type_I         351
Obesity_Type_III       324
Obesity_Type_II        297
Overweight_Level_I     290
Overweight_Level_II    290
Normal_Weight          287
Insufficient_Weight    272
Name: NObeyesdad, dtype: int64

In [50]:
data.rename(columns = {'NObeyesdad': 'Weight_Status'}, inplace=True)
data

,Gender,Age,Height (meters),Weight (Kg),Family_history_with_overweight,Frequent_consumption_high_caloric_food,Frequency_consumption_vegetables,Number_main_meals_a_day,Consumption_food_between_meals,SMOKE,Daily_water_consumption,Calories_consumption_monitoring,Physical_activity_frequency (days/week),Time_using_technology_devices (hours),Consumption_of_alcohol,Transportation_used,Weight_Status
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,Female,21.0,1.71,131.4,yes,yes,3.0,3.0,Sometimes,no,1.7,no,2.0,0.9,Sometimes,Public_Transportation,Obesity_Type_III
2107,Female,22.0,1.75,133.7,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0,0.6,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,23.0,1.75,133.7,yes,yes,3.0,3.0,Sometimes,no,2.1,no,1.0,0.6,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,24.0,1.74,133.3,yes,yes,3.0,3.0,Sometimes,no,2.9,no,1.0,0.6,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,24.0,1.74,133.5,yes,yes,3.0,3.0,Sometimes,no,2.9,no,1.0,0.7,Sometimes,Public_Transportation,Obesity_Type_III